import React from 'react'
import { useBrowser } from '../../context/BrowserContext'

const SummonedPage = () => {
  const { summonedPageContent } = useBrowser()

  if (!summonedPageContent) {
    return (
      <div className="retro-page summoned-page">
        <center>
          <br /><br />
          <table border="3" cellPadding="20" bgcolor="#FFFFCC">
            <tr>
              <td>
                <font face="Arial" size="4" color="#CC0000">
                  <b>⚠️ No page has been summoned yet!</b>
                </font>
                <br /><br />
                <font face="Verdana" size="2">
                  Click the "Summon Cursed Page" button in the toolbar to conjure 
                  a new haunted webpage from the digital void...
                </font>
              </td>
            </tr>
          </table>
        </center>
      </div>
    )
  }

  return (
    <div className="retro-page summoned-page">
      <style>{summonedPageContent.css}</style>
      <div 
        dangerouslySetInnerHTML={{ __html: summonedPageContent.html }}
      />
      <br />
      <center>
        <table border="2" cellPadding="10" bgcolor="#E6E6FA">
          <tr>
            <td>
              <font face="Arial" size="1" color="#666666">
                ✨ This page was summoned from the digital afterlife ✨<br />
                Theme: {summonedPageContent.theme} | Generated by AI Necromancy
              </font>
            </td>
          </tr>
        </table>
      </center>
    </div>
  )
}

export default SummonedPage
